AzureKeys:
  
  DocumentIntelligence:
    KEY_1: 
    KEY_2: 
    AZURE_ENDPOINT: https://termsheets.cognitiveservices.azure.com/
    AZURE_REGION: eastus
    MODEL_ID: ts2
  
  BlobStorage:
    CONNECTION_STRING: 
    CONTAINER_NAME: ts2